# Generated by Django 3.2.9 on 2021-11-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_user_date_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='work_names',
            field=models.CharField(max_length=20),
        ),
    ]
